name: Deploy Development Build

# Trigger on push to "master" branch
on:
  push:
    branches:
      - master
    paths:
      - .github/**
      - start-nexus-repository-manager.sh 
      - Dockerfile

jobs:
  build_deploy_to_registry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: crazy-max/ghaction-docker-buildx@v3.1.0

      - name: Docker login
        run: docker login --username '${{secrets.DOCKER_USERNAME}}' --password '${{secrets.DOCKER_PASSWORD}}'

      - name: Build + Push image (tag = git release tag)
        run: |
          docker buildx build \
            --platform "linux/arm/v7,linux/arm64" \
            --tag "${{secrets.DOCKER_USERNAME}}/nexus3:${GITHUB_REF#refs/tags/}" \
            --output "type=image,push=true" \
            --file ./Dockerfile .
      - name: Build + Push image ("latest")
        run: |
          docker buildx build \
            --platform "linux/arm/v7,linux/arm64" \
            --tag "${{secrets.DOCKER_USERNAME}}/nexus3:latest" \
            --output "type=image,push=true" \
            --file ./Dockerfile .
