name: Deploy Development Build

# Trigger on push to "master" branch
on:
  push:
    branches:
      - master
    paths:
      - .github/**
      - start-nexus-repository-manager.sh 
      - Dockerfile

jobs:
  build_deploy_to_registry:
    runs-on: ubuntu-latest
    steps:
            - uses: actions/checkout@v1
            - name: Login to DockerHub Registry
              run: echo ${{ secrets.docker_username }} | docker login -u ${{ secrets.docker_password }} --password-stdin
            - name: Get the version
              id: vars
              run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
              
            - name: Build the tagged Docker image
              run: docker build . --file Dockerfile --tag mjayson/nexus3-rpi:${{steps.vars.outputs.tag}}
            
            - name: Push the tagged Docker image
              run: docker push mjayson/nexus3-rpi:${{steps.vars.outputs.tag}}
            
            - name: Build the latest Docker image
              run: docker build . --file Dockerfile --tag mjayson/nexus3-rpi:latest
            
            - name: Push the latest Docker image
              run: docker push mjayson/nexus3-rpi:latest

