name: Deploy Development Build

# Trigger on push to "master" branch
on:
  push:
    branches:
      - master
    paths:
      - .github/**
      - start-nexus-repository-manager.sh 
      - Dockerfile

jobs:
  build_deploy_to_registry:
    runs-on: ubuntu-latest
    steps:
    - name: Publish to Registry
      uses: docker/build-push-action@v1
      with:
        repository: mjayson/nexus3-rpi
        username: ${{ secrets.docker_username }}
        password: ${{ secrets.docker_password }}
